### ISSUE TITLE
macOS: endian.h include problem in crypto/os_int.h

### ISSUE THREAD

**Issue by ilovezfs** [pfalcon/axtls#1]
See https://github.com/micropython/micropython/issues/2143.

(Also reported upstream to Cameron Rich via email: http://axtls.sourceforge.net/contact.htm)

The build of axTLS fails on macOS because endian.h is in the "machine" subdirectory. But it's actually not even necessary to explicitly #include <machine/endian.h> because it's already included from <sys/types.h>.

The problematic include is in the file is crypto/os_int.h

This is causing the build of micropython to fail since it depends on axTLS (via a submodule pointing to the fork at https://github.com/pfalcon/axtls). The micropython issue concerning the endian.h bug is here: https://github.com/micropython/micropython/issues/2143

I'm patching axTLS as part of the micropython "formula" on Homebrew, but it would be great if this could be fixed upstream in svn://svn.code.sf.net/p/axtls and then get picked up by the pfalcon fork, so that the patching is no longer necessary.

**Comment by pfalcon** [comment]
So, where's the patch?

**Comment by ilovezfs** [comment]
The patch is delete the include.

```
    inreplace "lib/axtls/crypto/os_int.h", "#include <endian.h>", ""
```

**Comment by ilovezfs** [comment]
(It should be restricted to darwin, of course)

**Comment by ilovezfs** [comment]
@pfalcon Homebrew PR now refreshed: https://github.com/Homebrew/homebrew-core/pull/2607/files#diff-8ea455c1c60c376aa6f749bfba8dc8cbR23

**Comment by pfalcon** [comment]
> (It should be restricted to darwin, of course)

So, there's productive way to resolve it: please submit pull request with change you tested to fix macosx build and not regress other builds.

Even more productive way is to contribute to micropython a .travis.yml which builds it for macosx (I heard TravisCI supports macosx builds).

Otherwise, it will wait for someone to decrypt/wade thru all that.

**Comment by ilovezfs** [comment]
This really needs to be fixed by Cameron upstream in svn however he sees fit, and the rest will take care of itself.

**Comment by ilovezfs** [comment]
@pfalcon upstream has fixed this

https://sourceforge.net/p/axtls/code/256/tree//trunk/crypto/os_int.h?diff=511c3f4934309d74f9522c0d:255

and has tagged a new version

https://sourceforge.net/p/axtls/code/259/tree/tags/release-1.5.4/

~~It would be great if you could refresh your fork with the latest.~~

Ah, I see it's in 9776795d9f589158b191874560b483c48192c1a9 but not the 1.8.2 release.

> I heard TravisCI supports macosx builds

It does. Here's an example from Homebrew/science, which tests both macOS El Capitan (10.11) and Linux (for the sake of Linuxbrew):

https://github.com/Homebrew/homebrew-science/blob/master/.travis.yml

(Separately, they also test 10.11, 10.10, and 10.9 via Jenkins)
