### ISSUE TITLE
os_port.h

### ISSUE THREAD

**Issue by chiefenne** [pfalcon/axtls#2]
I try to build axtls on Windows 10 using MSYS2.

In the file os_port.h I find the statement:
   os_port_micropython.h

When I changed it to
   #include <os_port_micropython.h>
I can build axtls.

I have no experience in C, so I don't know wether the intended behaviour can be created by any compiler or linker option.

**Comment by pfalcon** [comment]
os_port.h is a symlink to os_port_micropython.h originally. It's recommended to build on Linux (via a VM or otherwise) to avoid confusion.
